import os

# --- BINGX API ---
API_KEY = os.getenv("BINGX_API_KEY")
API_SECRET = os.getenv("BINGX_API_SECRET")
BINGX_BASE = "https://open-api.bingx.com"

# --- TELEGRAM ---
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

# --- DATABASE ---
DATABASE_URL = os.getenv("DATABASE_URL")  # Render PostgreSQL URL

# --- DEFAULT TRADE SETTINGS ---
LEVERAGE = 20
TRADE_SIZE = 200
TP_PERCENT = 0.5
SL_PERCENT = 40

# --- DCA SETTINGS ---
DCA_COUNT = 4
DCA_DEVIATION_PERCENT = 5
DCA_VOLUME_MULTIPLIER = 2

# --- AUTO CLOSE ---
AUTO_CLOSE_FROM_DCA = 1
AUTO_CLOSE_BUFFER = 0.0

# --- LIMITS ---
MAX_OPEN_POSITIONS = 20
